import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Forum&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://cdn.lineicons.com/4.0/lineicons.css"
          rel="stylesheet"
        ></link>
        <link
          rel="stylesheet"
          href="/node_modules/owl.carousel/dist/assets/owl.carousel.min.css"
        />
        <link
          rel="stylesheet"
          href="/bower_components/owl.carousel/dist/assets/owl.carousel.min.css"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
